### PR TITLE
Replace cl with cl-lib

### PR DESCRIPTION
**Pull request by jabranham**
cl was obsoleted with GNU Emacs 24.3 and now issues byte compile warnings, especially when required at runtime. 

This PR makes htmlize prefer the namespace clean functions from cl-lib instead of cl. 

This'll break compatibility with GNU Emacs 24.2 and lower. I couldn't find what the minimum required version of Emacs is.

### CODE REVIEW

**Comment by hniksic** [comment]
The point of the `cl` extensions is to give the code a CL-style look&feel, and enforcing the `cl-` prefix removes that part of the appeal. The extensions have been shipped with Emacs for 20+ years, and used by `htmlize` since the beginning. Unless there is a serious indication that the non-prefixed symbols are to be removed altogether, I would prefer to keep using them.

Is it possible to silence the warnings instead? Most byte-compilation warnings have a way to turn them off.

**Comment by jabranham** [comment]
> Is it possible to silence the warnings instead?

Yes, they already are. 

I looked into this because `cl` isn't supposed to be required by packages at runtime. I had forgotten to require it at compile time in an unrelated file and had problems tracking down the bug because htmlize loads it at runtime (so my compiler knew about it but not the user's).

**Comment by phikal** [comment]
Since [`cl` has been declared obsolete](http://git.savannah.gnu.org/cgit/emacs.git/commit/etc/NEWS?id=1d8b5bc8dd543ada2f3c46436e43ea27faa3cd0e), could this issue be reconsidered again?

**Comment by hniksic** [comment]
@phikal Yes, we should move away from `cl`. A problem with the original change was that it was incompatible with Emacsen prior to 24.3, which broke it on the Emacs I was using at the time.

**Comment by takaxp** [comment]
We have a good example here:
https://github.com/emacs-php/php-mode/pull/203/files#diff-6caa62262a5e21bf011a728cd018371fR91

**Comment by wasamasa** [comment]
Emacs 24.4 is from 2014. Do you really test with a six years old version of that text editor? Even on Debian oldstable it's 24.5 and cl-lib should just work. Please let's not bend over for this in the wake of Emacs 27.1 adding one more incentive to upgrade and now shows a warning when `(require 'cl)` is used at runtime (as is the case here).

**Pull request merged**
